# Spring ?????
spring:
  datasource:
    # MySQL ?????????????????????/?????
    url: jdbc:mysql://localhost:3306/sys_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # ????????
    username: root
    # ?????????????MySQL???????
    password: 123456
    # MySQL 8.x ??????????????
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Druid ????????????????
    druid:
      # ??????????????
      initial-size: 5
      # ??????????????
      min-idle: 5
      # ?????????????
      max-active: 20
      # ???????????????????
      max-wait: 60000

# MyBatis ??
mybatis:
  # Mapper XML ??????? MyBatis ???? SQL ?????
  mapper-locations: classpath:mapper/*.xml
  # ????????? XML ???????
  type-aliases-package: com.fast.logintest.domain
